/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.redisson.config.Config
import org.redisson.Redisson
import org.redisson.codec.JsonJacksonCodec
import org.redisson.api.RedissonClient

class App {
    fun getRedissonClient(): RedissonClient {
        val config = Config().apply {
            codec = JsonJacksonCodec()
        }
        return Redisson.create(config)
    }
}

fun main() {
    App().getRedissonClient()
}
